# Generated by Django 3.0.8 on 2020-11-23 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrarFilialModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=30)),
                ('tipo', models.CharField(choices=[('Fabricadora', 'Fabricadora'), ('Distribuidora y Ventas', 'Distribuidora y Ventas')], default='Fabricadora', max_length=22)),
                ('direccion', models.CharField(max_length=200)),
            ],
        ),
    ]
