# Generated by Django 3.0.8 on 2020-11-23 21:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppCalzado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrarfilialmodel',
            name='fechaCreacion',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
