# Generated by Django 3.0.8 on 2020-11-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCalzado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroextrasmodel',
            name='cantidadHorasExtras',
            field=models.PositiveIntegerField(),
        ),
    ]
