# Generated by Django 3.0.8 on 2020-11-24 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCalzado', '0004_auto_20201123_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrarTrabajadoresModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('celular', models.IntegerField()),
                ('email', models.EmailField(max_length=30)),
                ('tipo', models.CharField(choices=[('Trabajador Base', 'Trabajador Base'), ('Directivo', 'Directivo'), ('Presidente Directivo', 'Presidente Directivo')], default='Trabajador Base', max_length=30)),
                ('dpi', models.IntegerField()),
                ('fechaCreacion', models.DateField()),
            ],
        ),
    ]
